CREATE DATABASE AB_FLORICULTURA
USE AB_FLORICULTURA
GO

CREATE TABLE FORNECEDOR(
	CODFORNECEDOR 	INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
	CPFCNPJFORNECEDOR VARCHAR(14) NOT NULL,
	RAZAOSOCIAL VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	NOMEFANTASIA VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	TIPOEMPRESA VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	INSCRICAOESTADUAL VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	INSCRICAOMUNICIPAL VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DATAINCLUSAO SMALLDATETIME NOT NULL,
	STATUSFORNECEDOR VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
)
GO

CREATE TABLE PEDIDO_FORNECEDOR(
	CODPEDIDOFORNECEDOR INT PRIMARY KEY IDENTITY (1,50),
	CODFORNECEDOR INT NOT NULL,
	RAZAOSOCIAL VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NOMEFANTASIA VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DATAHORAPEDIDO SMALLDATETIME NOT NULL,
	VALORTOTALPEDIDOFORNECEDOR 	NUMERIC(18,2) NOT NULL,
CONSTRAINT FK_PEDIDO_FORNECEDOR FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDOR(CODFORNECEDOR)
)
GO

CREATE TABLE CONTATO_FORNECEDOR(
	CODCONTATO	INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
	NUMEROCONTATO VARCHAR(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TIPO VARCHAR(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CODFORNECEDOR INT,
CONSTRAINT FK_TELEFONE_FORNECEDOR FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDOR(CODFORNECEDOR)
)
GO


CREATE TABLE ENDERECO_FORNECEDOR(
	CODENDERECO INT PRIMARY KEY IDENTITY (1,1), 
	CEP VARCHAR(7) NOT NULL,
	LOUGRADOURO VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NUMERO VARCHAR(5) NOT NULL,
	COMPLEMENTO VARCHAR(50)COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CIDADE VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BAIRRO VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	UF VARCHAR(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CODFORNECEDOR	INT,
CONSTRAINT FK_ENDERECO_FORNECEDOR FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDOR(CODFORNECEDOR)
)
GO


CREATE TABLE CATEGORIA(
	CODCATEGORIA INT PRIMARY KEY IDENTITY (1,1) NOT NULL,  
	DESCRICAOCATEGORIA 	VARCHAR (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TIPOCATEGORIA 	VARCHAR (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, --// PRINCIPAL OU SUBCATEGORIA
	STATUSCATEGORIA VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO

CREATE TABLE PRODUTO(
	CODPRODUTO 	INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMEPRODUTO 	VARCHAR (50) NOT NULL,
	CODIGOBARRASPRODUTO VARCHAR (50) NOT NULL,
	PRECOCOMPRAPRODUTO 	NUMERIC(18,2) NOT NULL,
	PRECOVENDAPRODUTO 	NUMERIC(18,2) NOT NULL,
	QUANTIDADEPRODUTO 	INT DEFAULT 0 NOT NULL,
	DATAVALIDADE SMALLDATETIME NOT NULL,
	CODFORNECEDOR 	INT NOT NULL,
	DATACADASTRADA 	SMALLDATETIME NOT NULL,
	CODCATEGORIA 	INT NOT NULL,
	CODSUBCATEGORIA INT NOT NULL,
	STATUSPRODUTO 	VARCHAR (8) NOT NULL
CONSTRAINT FK_CATEGORIA FOREIGN KEY (CODCATEGORIA) REFERENCES  CATEGORIA(CODCATEGORIA),
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDOR(CODFORNECEDOR),
CONSTRAINT FK_SUBCATEGORIA FOREIGN KEY (CODCATEGORIA) REFERENCES CATEGORIA(CODCATEGORIA)
)
GO

CREATE TABLE CLIENTE(
	CODCLIENTE 	INT PRIMARY KEY IDENTITY(1,1),
	NOMECLIENTE 	VARCHAR (50) NOT NULL,
	CPFCLIENTE 	VARCHAR (14) NOT NULL,
	LOGRADOUROCLIENTE 	VARCHAR (40) NOT NULL,
	NUMEROCLIENTE 	VARCHAR (12) NOT NULL,
	COMPLEMENTOCLIENTE 	VARCHAR (30) NOT NULL ,
	CEPCLIENTE 	VARCHAR (15) NOT NULL,
	BAIRROCLIENTE 	VARCHAR (50) NOT NULL,
	CIDADECLIENTE 	VARCHAR (30) NOT NULL,
	DATANASCIMENTO 	SMALLDATETIME NOT NULL,
	STATUSCLIENTE 	VARCHAR(8) NOT NULL
)
GO

-- SEPARAR CONTATO E EMAIL, TANTO PARA USUARIO COMO PARA CLIENTE
CREATE TABLE CONTATO_CLIENTE(
	CODCONTATO	INT PRIMARY KEY IDENTITY (1,1), 
	NUMEROCONTATO VARCHAR(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TIPO VARCHAR(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CODCLIENTE INT,
CONSTRAINT FK_CONTATO_CLIENTE_FORNECEDOR FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE)
)
GO
CREATE TABLE EMAIL_CLIENTE(
	CODEMAIL INT PRIMARY KEY IDENTITY (1,1), 
	EMAIL VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CODCLIENTE	INT NOT NULL,
CONSTRAINT FK_EMAIL_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE)
)
GO

CREATE TABLE ENDERECO_CLIENTE(
	CODENDERECO INT PRIMARY KEY IDENTITY (1,1), 
	CEP VARCHAR(7) NOT NULL,
	LOUGRADOURO VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NUMERO VARCHAR(5) NOT NULL,
	COMPLEMENTO VARCHAR(50)COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CIDADE VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BAIRRO VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	UF VARCHAR(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CODCLIENTE	INT
CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE)
)
GO

CREATE TABLE ENCOMENDA(
	CODENCOMENDA 	INT PRIMARY KEY IDENTITY(1,50),
	DATAENCOMENDA 	SMALLDATETIME NOT NULL,
	DATAENTREGA 	SMALLDATETIME NOT NULL,
	CODCLIENTE 	INT NOT NULL,
	VALORENCOMENDA 	NUMERIC (18,2) NOT NULL,
	STATUSENCOMENDA 	VARCHAR(8) NOT NULL
	--//VENDEDOR
CONSTRAINT FK_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES  CLIENTE(CODCLIENTE)
)
GO

CREATE TABLE ITEM_ENCOMENDA(
	CODITEMENCOMENDA 	INT PRIMARY KEY IDENTITY (1,1), 
	CODENCOMENDA 	INT NOT NULL,
	CODPRODUTO 	INT NOT NULL,
	QUANTIDADE 	INT NOT NULL,
	SUBTOTAL NUMERIC (18,2) NOT NULL,
CONSTRAINT FK_PRODUTO FOREIGN KEY (CODPRODUTO) REFERENCES  PRODUTO(CODPRODUTO),
CONSTRAINT FK_ENCOMENDA FOREIGN KEY (CODENCOMENDA) REFERENCES ENCOMENDA(CODENCOMENDA)
)
GO



CREATE TABLE ITENS_PEDIDO_FORNECEDOR(
	CODITENSPEDIDOFORNECEDOR 	INT PRIMARY KEY IDENTITY(1,1),
	CODPRODUTO INT NOT NULL,
	QUANTIDADEITENSPEDIDOFORNECEDOR INT NOT NULL,
	SUBTOTALITENSPEDIDOFORNECEDOR NUMERIC (18,2) NOT NULL,
	CODPEDIDOFORNECEDOR INT NOT NULL,
CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTO(CODPRODUTO),
CONSTRAINT FK_ITEM_PEDIDO_FORNECEDOR FOREIGN KEY (CODPEDIDOFORNECEDOR) REFERENCES PEDIDO_FORNECEDOR(CODPEDIDOFORNECEDOR)
)
GO

CREATE TABLE USUARIO(
	CODUSUARIO 	INT PRIMARY KEY IDENTITY(1,1),
	LOGINUSUARIO VARCHAR (50) NOT NULL,
	SENHAUSUARIO VARCHAR (40) NOT NULL,
	STATUSUSUARIO VARCHAR(8) NOT NULL,
	NOMEUSUARIO VARCHAR(70) NOT NULL,
	NIVELACESSO VARCHAR (10) NOT NULL
)
GO

CREATE TABLE MOTIVO_SAIDA_PRODUTO(
	CODMOTIVOSAIDAPRODUTO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAOMOTIVOSAIDAPRODUTO VARCHAR (60) NOT NULL,
	STATUSMOTIVOSAIDAPRODUTO VARCHAR(8) NOT NULL
)
GO

CREATE TABLE SAIDA_PRODUTO (
	CODSAIDAPRODUTO INT PRIMARY KEY IDENTITY(1,1),
	CODMOTIVOSAIDAPRODUTO INT NOT NULL,
	DATASAIDAPRODUTO SMALLDATETIME NOT NULL,
	QUANTIDADESAIDAPRODUTO INT NOT NULL,
	CODPRODUTO INT NOT NULL
CONSTRAINT FK_SAIDA_PRODUTO FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTO(CODPRODUTO),
CONSTRAINT FK_MOTIVO_SAIDA_PRODUTO FOREIGN KEY (CODMOTIVOSAIDAPRODUTO) REFERENCES MOTIVO_SAIDA_PRODUTO(CODMOTIVOSAIDAPRODUTO)
)
GO

CREATE TABLE MOTIVO_ENTRADA_PRODUTO (
	CODMOTIVOENTRADAPRODUTO 	INT PRIMARY KEY IDENTITY(1,1),
 	DESCRICAOMOTIVOENTRADAPRODUTO VARCHAR (40) NOT NULL
)
GO

CREATE TABLE ENTRADA_PRODUTO(
	CODENTRADAPRODUTO	INT PRIMARY KEY IDENTITY(1,1),
 	QUANTIDADEENTRADAPRODUTO INT NOT NULL,
 	DATAENTRADAPRODUTO SMALLDATETIME NOT NULL,
 	CODMOTIVOENTRADAPRODUTO INT NOT NULL,
 	LOTEPRODUTO VARCHAR(30),
 	DATAVALIDADELOTE SMALLDATETIME,
 	CODFORNECEDOR INT,
 	CODPRODUTO INT,
 	ATIVIDADEENTRADA VARCHAR(30),
CONSTRAINT FK_ENTRADA_PRODUTO FOREIGN KEY (codProduto) REFERENCES PRODUTO(codProduto),
CONSTRAINT FK_FORNECEDOR_PRODUTO FOREIGN KEY (codFornecedor) REFERENCES FORNECEDOR(codFornecedor),
CONSTRAINT FK_MOTIVO_ENTRADA_PRODUTO FOREIGN KEY (codMotivoEntradaProduto) REFERENCES MOTIVO_ENTRADA_PRODUTO(codMotivoEntradaProduto)
)
GO

CREATE TABLE VENDA(
	CODVENDA 	INT PRIMARY KEY IDENTITY(1,1),
	DATAVENDA 	SMALLDATETIME NOT NULL,
	VALORVENDA 	NUMERIC (18,2) NOT NULL,
	CODCLIENTE 	INT,
	CODUSUARIO INT
CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE),
CONSTRAINT FK_VENDA_USUARIO FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO(CODUSUARIO)
)
GO

CREATE TABLE ITENS_VENDA(
	CODITENSVENDA 	INT PRIMARY KEY IDENTITY(1,1),
	CODPRODUTO 	INT,
	CODVENDA 	INT,
	QUANTIDADEITEM 	INT NOT NULL,
	SUBTOTAL 	NUMERIC(18,2) NOT NULL,
	CONSTRAINT FK_ITENS_VENDA_PRODUTO FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTO(CODPRODUTO),
	CONSTRAINT FK_VENDA FOREIGN KEY (CODVENDA) REFERENCES VENDA(CODVENDA)
)
GO

CREATE TABLE FORMA_PAGAMENTO(
	CODFORMAPAGAMENTO 	INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAOFORMAPAGAMENTO 	VARCHAR (20) NOT NULL,
	CODVENDA INT NOT NULL
	CONSTRAINT FK_FORMAPAG_VENDA FOREIGN KEY (CODVENDA) REFERENCES VENDA(CODVENDA)
)
GO


CREATE TABLE MOTIVO_ENTRADA_CAIXA(
	CODMOTIVOENTRADACAIXA 	INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAOMOTIVOENTRADACAIXA 	VARCHAR (30) NOT NULL ,
	STATUSMOTIVOENTRADACAIXA 	VARCHAR (8) NOT NULL
)
GO

CREATE TABLE CAIXA(
	CODCAIXA 	INT PRIMARY KEY IDENTITY(1,1),
	STATUSCAIXA 	VARCHAR (8),
	VALORFINALCAIXA 	NUMERIC(18,2),
	VALORINICIALCAIXA 	NUMERIC(18,2),
	DATACAIXA 	SMALLDATETIME
)
GO

CREATE TABLE ENTRADA_CAIXA(
	CODENTRADACAIXA 	INT PRIMARY KEY IDENTITY(1,1),
	VALORENTRADACAIXA 	NUMERIC (18,2),
	DATAENTRADACAIXA 	SMALLDATETIME ,
	CODMOTIVOENTRADACAIXA 	INT,
	STATUSENTRADACAIXA 	VARCHAR (8),
	CODFORMAPAGAMENTO 	INT,
	CODCAIXA 	INT,
CONSTRAINT FK_ENTRADA_CAIXA FOREIGN KEY (CODCAIXA) REFERENCES CAIXA(CODCAIXA),
CONSTRAINT FK_ENTRADA_FORMA_PAGAMENTO FOREIGN KEY (CODFORMAPAGAMENTO) REFERENCES FORMA_PAGAMENTO(CODFORMAPAGAMENTO),
CONSTRAINT FK_MOTIVO_ENTRADA_CAIXA FOREIGN KEY (CODMOTIVOENTRADACAIXA) REFERENCES MOTIVO_ENTRADA_CAIXA(CODMOTIVOENTRADACAIXA)
)
GO


CREATE TABLE MOTIVO_SAIDA_CAIXA(
	CODMOTIVOSAIDACAIXA 	INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAOMOTIVOSAIDA 	VARCHAR (30),
	STATUSMOTIVOSAIDACAIXA 	VARCHAR(8) 
)
GO

CREATE TABLE SAIDA_CAIXA(
	CODSAIDACAIXA INT PRIMARY KEY IDENTITY(1,1),
	VALORSAIDACAIXA 	NUMERIC(18,2),
	DATASAIDACAIXA 	SMALLDATETIME,
	STATUSSAIDACAIXA 	VARCHAR (8),
	CODMOTIVOSAIDACAIXA 	INT,
	CODCAIXA 	INT,
CONSTRAINT FK_SAIDA_CAIXA FOREIGN KEY (CODCAIXA) REFERENCES CAIXA(CODCAIXA),
CONSTRAINT FK_MOTIVO_SAIDA_CAIXA FOREIGN KEY (CODMOTIVOSAIDACAIXA) REFERENCES MOTIVO_SAIDA_CAIXA(CODMOTIVOSAIDACAIXA)
)
GO

CREATE TABLE PAGAMENTO(
	CODPAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
	VALORPAGAMENTO 	NUMERIC(18,2) NOT NULL,
	DATAPAGAMENTO DATETIME NOT NULL,
	CODFORMAPAGAMENTO 	INT,
	CODVENDA INT,
	CODUSUARIO 	INT,
CONSTRAINT FK_FORMA_PAGAMENTOS FOREIGN KEY (CODFORMAPAGAMENTO) REFERENCES FORMA_PAGAMENTO(CODFORMAPAGAMENTO),
CONSTRAINT FK_VENDA_PAGAMENTO FOREIGN KEY (CODVENDA) REFERENCES VENDA(CODVENDA),
CONSTRAINT FK_USUARIO FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO(CODUSUARIO)
)
GO

--INSERÇÃO DA FORMA DE PAGAMENTO
/*INSERT INTO FORMA_PAGAMENTO(DESCRICAOFORMAPAGAMENTO)
VALUES ('Dinheiro'),
	   ('Débito'),
       ('Crédito'),
       ('Pix')*/

GO